stages:
  - format
  - build
  - test

# -------------------------------- GLOBAL JOB ---------------------------------- #
format_and_lint:
  image: node:16-alpine
  stage: format
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run format:check
    - npm run lint

build-code-job:
  stage: build
  script:
    - echo "Check build stage success"

test-code-job1:
  stage: test
  script:
    - echo "Check test stage success"